# -*-python-*-

import infinity.formats.are_v10
import infinity.formats.are_v91
import infinity.formats.baf
import infinity.formats.bam
import infinity.formats.bcs
import infinity.formats.biff
import infinity.formats.bmp
import infinity.formats.chr_v10
import infinity.formats.chr_v12
import infinity.formats.chr_v20
import infinity.formats.chr_v22
import infinity.formats.chr_v90
import infinity.formats.chui
import infinity.formats.cre_v10
import infinity.formats.cre_v12
import infinity.formats.cre_v22
import infinity.formats.cre_v90
import infinity.formats.d2a
import infinity.formats.dlg
import infinity.formats.eff_v20
import infinity.formats.gam
import infinity.formats.gam_v11
import infinity.formats.gam_v22
import infinity.formats.ids
import infinity.formats.ini
import infinity.formats.itm_v1
import infinity.formats.itm_v11
import infinity.formats.itm_v20
import infinity.formats.key
import infinity.formats.mos
import infinity.formats.mus
import infinity.formats.plt
import infinity.formats.pro
import infinity.formats.sav
import infinity.formats.spl
import infinity.formats.stor_v10
import infinity.formats.stor_v11
import infinity.formats.stor_v90
import infinity.formats.tis
import infinity.formats.tlk
import infinity.formats.var
import infinity.formats.vvc
import infinity.formats.wavc
import infinity.formats.wed
import infinity.formats.wfx
import infinity.formats.wmap
